In [1]:
1 + 2

3

In [2]:
5 + 7

12

# MarkDown

In [3]:
data = [2*i for i in range(100)]

In [4]:
data[:10]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
%timeit L = [i**2 for i in range(1000)]

218 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%time L = [i**2 for i in range(1000)]

CPU times: user 273 µs, sys: 0 ns, total: 273 µs
Wall time: 276 µs


In [15]:
import numpy as np

In [16]:
np.__version__

'1.16.2'

In [18]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr.dtype

dtype('int64')

In [20]:
nparr[5]=5.003

In [21]:
nparr.dtype

dtype('int64')

In [22]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.zeros(shape=(3,5),dtype=int,fill_value=666)

TypeError: 'fill_value' is an invalid keyword argument for zeros()

In [28]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])